Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
