source 'https://rubygems.org'

gem 'chunky_png'
gem 'memprof2'
gem 'mnist'
gem 'progressbar'
gem 'pry'
gem 'pycall', require: 'pycall/import'
gem 'rspec'
gem 'rubocop', require: false
gem 'simplecov', require: false
gem 'sinatra', require: false
gem 'slim'
